title: Edgar Davtyan
# logo: /assets/img/headshot_circle.png
#description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
author:
  name: Edgar Davtayn
  email: davtyan.edd@gmail.com
