title: Edgar Davtyan
logo: /assets/img/profile_pic.png
#description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
social_links:
  github: https://github.com/EDavtyan
  linkedin: https://www.linkedin.com/in/davtyaned/
  email: mailto:davtyan.edd@gmail.com
